import type { Metadata } from "next";
import localFont from "next/font/local";

import Navigation from "@/components/Navigation/Navigation";

import "./globals.css";

const inter = localFont({
  src: "../public/assets/fonts/GummyBear.ttf",
  variable: "--customFont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
